# Generated by Django 5.0.1 on 2024-01-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('user_fullname', models.CharField(max_length=255)),
                ('house_img', models.ImageField(upload_to='image_house/')),
                ('description', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('partnership_logo', models.ImageField(upload_to='Banner_photo/')),
                ('image', models.ImageField(upload_to='Banner/')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_logo', models.ImageField(upload_to='my_logo/')),
                ('description', models.CharField(max_length=255)),
                ('facebook', models.CharField(max_length=255)),
                ('twitter', models.CharField(max_length=255)),
                ('instagramm', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.IntegerField()),
                ('email', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Presintaiton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(upload_to='video_img/')),
            ],
        ),
        migrations.CreateModel(
            name='Recomendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='Recomendation_photo/')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user_name', models.CharField(max_length=255)),
                ('adress', models.CharField(max_length=255)),
                ('user_photo', models.ImageField(upload_to='user_photo/')),
                ('tag', models.CharField(choices=[('popular', 'popular'), ('new house', 'new house'), ('best deals', 'best deals')], max_length=25)),
                ('type', models.CharField(choices=[('house', 'house'), ('villa', 'villa'), ('apartment', 'apartment')], max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='Testimonial/')),
                ('user_title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('user_photo', models.ImageField(upload_to='Test_photo/')),
                ('user_job', models.CharField(max_length=255)),
                ('user_name', models.CharField(max_length=255)),
                ('reting', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('user_photo', models.ImageField(upload_to='user_photo/')),
                ('user_name', models.CharField(max_length=255)),
                ('user_job', models.CharField(max_length=255)),
                ('detail', models.ManyToManyField(to='main.detail')),
                ('presintation', models.ManyToManyField(to='main.presintaiton')),
            ],
        ),
    ]
